return {
  "hedyhli/outline.nvim",
  opts = {
    symbols = {
      filter = {
        python = { "Property", "Module", "Variable", exclude = true },
        cpp = false,
      },
      icons = {
        File = { icon = " ", hl = "Identifier" },
        Module = { icon = "󰆧 ", hl = "Include" },
        Namespace = { icon = "󰅪 ", hl = "Include" },
        Package = { icon = "󰏗 ", hl = "Include" },
        Class = { icon = " ", hl = "Type" },
        Method = { icon = "ƒ ", hl = "Function" },
        Property = { icon = "  ", hl = "Identifier" },
        Field = { icon = " ", hl = "Identifier" },
        Constructor = { icon = " ", hl = "Special" },
        Enum = { icon = " ", hl = "Type" },
        Interface = { icon = " ", hl = "Type" },
        Function = { icon = "ƒ ", hl = "Function" },
        Variable = { icon = "󰫧 ", hl = "Constant" },
        Constant = { icon = " ", hl = "Constant" },
        String = { icon = "󰅳 ", hl = "String" },
        Number = { icon = "# ", hl = "Number" },
        Boolean = { icon = " ", hl = "Boolean" },
        Array = { icon = " ", hl = "Constant" },
        Object = { icon = "⦿ ", hl = "Type" },
        Key = { icon = " ", hl = "Type" },
        Null = { icon = "󰟢 ", hl = "Type" },
        EnumMember = { icon = " ", hl = "Identifier" },
        Struct = { icon = " ", hl = "Structure" },
        Event = { icon = " ", hl = "Type" },
        Operator = { icon = " ", hl = "Identifier" },
        TypeParameter = { icon = "𝙏 ", hl = "Identifier" },
        Component = { icon = "󰅴 ", hl = "Function" },
        Fragment = { icon = "󰅴 ", hl = "Constant" },
        TypeAlias = { icon = " ", hl = "Type" },
        Parameter = { icon = " ", hl = "Identifier" },
        StaticMethod = { icon = " ", hl = "Function" },
        Macro = { icon = " ", hl = "Function" },
      },
    },
    symbol_folding = {
      auto_unfold = { only = true },
      autofold_depth = 2,
    },
    outline_items = {
      show_symbol_details = false,
    },
    keymaps = { close = {} },
    outline_window = { focus_on_open = false },
    providers = {
      priority = { "lsp", "coc", "markdown", "norg", "treesitter" },
    },
  },
  keys = {
    { "<leader>t", ":Outline<CR>", desc = "Outline", silent = true },
  },
  dependencies = { "epheien/outline-treesitter-provider.nvim" },
}
